import { ROLE } from "../constants/roles";

export const PERMISSIONS = {
  DASHBOARD: [ROLE.ADMIN, ROLE.KASIR, ROLE.OWNER],

  BARANG: [ROLE.ADMIN],

  KATEGORI: [ROLE.ADMIN],

  SATUAN: [ROLE.ADMIN],

  SUPPLIER: [ROLE.ADMIN],

  PELANGGAN: [ROLE.ADMIN, ROLE.KASIR],

  USER: [ROLE.ADMIN],

  PENJUALAN: [ROLE.ADMIN, ROLE.KASIR],

  PEMBELIAN: [ROLE.ADMIN],

  LAPORAN: [ROLE.ADMIN, ROLE.KASIR, ROLE.OWNER],

  KARTU_STOK: [ROLE.ADMIN, ROLE.OWNER],

  PENGATURAN: [ROLE.ADMIN],
} as const;
